# Generated by Django 4.2.23 on 2025-07-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_school_admin_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School_Admin',
        ),
    ]
