# Generated by Django 4.2.23 on 2025-07-14 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.school'),
        ),
    ]
