# Generated by Django 4.2.23 on 2025-07-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_request_school'),
    ]

    operations = [
    ]
