# Generated by Django 4.2.23 on 2025-07-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='form',
            field=models.FileField(blank=True, default='pending', null=True, upload_to='student_forms/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='permit',
            field=models.FileField(blank=True, default='pending', null=True, upload_to='student_permits/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='practical_result',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='theory_result',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=40),
        ),
    ]
