# Generated by Django 4.2.23 on 2025-07-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_form_alter_student_permit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='form',
            field=models.FileField(blank=True, null=True, upload_to='student_forms/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='permit',
            field=models.FileField(blank=True, null=True, upload_to='student_permits/'),
        ),
    ]
