# Generated by Django 4.2.23 on 2025-07-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_testrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestRequest',
        ),
    ]
